# -*- coding: utf-8 -*-
"""Assigment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X_w4IFBnMu0eMMxMsMSBv6QnXh-OzGFM
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile hola.cpp
# /* Fibonazi iterative */
# 
# #include <iostream>
# using namespace std;
# 
# int main() {
#     int a, b, c, d;
#     b = 0;
#     c = 1;
#     cin >> a;
#     for (int i=1; i <a ; i++){
# 
#         d = b + c;
#         b = c;
#         c = d;
#     }
#     cout << c << endl;
#     return 0;
# 
# }

!g++ hola.cpp -o hola
!./hola

# Commented out IPython magic to ensure Python compatibility.
# %%writefile hola.cpp
# /* Fibonazi recursive */
# 
# #include <iostream>
# using namespace std;
# 
# int fibo(int n){
#   if (n == 1){
#     return 1;
#   } else if (n == 0){
#     return 0;
#   } else {
#     return fibo(n-1) + fibo(n-2);
#   }
# }
# 
# int main() {
#     int n;
#     cin >> n;
#     cout << fibo(n) << endl;
#     return 0;
# }

!g++ hola.cpp -o hola
!./hola